Readme updates
SmartCasual/jingle-jam pull request #72
Opened 2021-07-17 09:37 UTC by ultratin

Updated readme with basic installation instruction and how to start the project.

Also added webpack-dev-server as part of the startup process for foreman

2021-07-17 10:50 UTC, elliotcm commented
Looks like you were partially pipped at the post by https://github.com/SmartCasual/jingle-jam/pull/71

There's some parts of this that I'd still like to keep, so I'll rebase it once the other PR is in.  Thanks!

2021-07-17 11:03 UTC, ultratin commented
@elliotcm sure thing. Happy to help!

2021-07-20 06:48 UTC, gormster commented
@ultratin ah, you gotta check the open PRs! sorry mate ;)

2021-07-21 07:43 UTC, elliotcm requested changes

2021-07-21 07:43 UTC, elliotcm commented on Procfile
> +webpack-dev-server: bin/webpack-dev-server
```suggestion
webpack-dev-server: bin/webpack-dev-server

```

2021-07-21 07:46 UTC, elliotcm approved these changes

2021-07-21 10:46 UTC, merged